version: "3.8"
services:

  Devops_Project:
    container_name: springboot-container
    image: soulaima2/devops_project
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url": "jdbc:mysql://localhost:3306/devops?createDatabaseIfNotExist=true",
      "spring.datasource.username": "root"
      }'
    ports:
      - 8082:8082
    depends_on:
      - mysqldb
    volumes:
      - app_data:/app/data

  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: devops
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  app_data: